### PR TITLE
macOS support

### PR DESCRIPTION
**Pull request by MartinZikmund**
**Description of Change**

Support for macOS

**Bugs Fixed**

- Related to issue #

Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix before sending PR.

**API Changes**

List all API changes here (or just put None), example:

Added: 
 
- `SKXamlCanvas.macOS`

**Behavioral Changes**

macOS support

**PR Checklist**

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Review by jeromelaban — APPROVED** [review]
Thanks Martin!

**Comment by MartinZikmund** [comment]
@jeromelaban Are the NuGet packages for Uno.SkiaSharp not published automatically? I could use the macOS support for https://github.com/verybadcat/CSharpMath/pull/121 🙂

**Comment by jeromelaban** [comment]
I can do that :) It's a manual publication process for now.

**Comment by MartinZikmund** [comment]
Thanks 😊!

**Pull request merged**
